### ISSUE TITLE
Add auto-merge approval for Dependabot PRs

### ISSUE THREAD

**Issue by atc0005** [atc0005/shared-project-resources#183]
## Overview

Example from `domainr/whois` project:

```yaml
name: Auto-merge ZoneDB

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    runs-on: ubuntu-22.04
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.6.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: ${{contains(steps.metadata.outputs.dependency-names, 'zonedb') && steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

I would be interested in auto-merging PRs targeting the `development` branch for most of the projects that I work with.

## References

- https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#approve-a-pull-request
- https://github.com/domainr/whois/blob/main/.github/workflows/automerge.yaml
  - https://github.com/domainr/whois/blob/71dca10ea0c8827f940ce2a1d9fa92bd9cc8c390/.github/workflows/automerge.yaml
